//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProId { get; set; }
        public string ProName { get; set; }
        public string ProContent { get; set; }
        public Nullable<int> CateId { get; set; }
        public Nullable<double> ProPrice { get; set; }
    }
}
