//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SinhVien", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceApp")]
    [System.SerializableAttribute()]
    public partial class SinhVien : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClassIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClassID {
            get {
                return this.ClassIDField;
            }
            set {
                if ((this.ClassIDField.Equals(value) != true)) {
                    this.ClassIDField = value;
                    this.RaisePropertyChanged("ClassID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pass {
            get {
                return this.PassField;
            }
            set {
                if ((object.ReferenceEquals(this.PassField, value) != true)) {
                    this.PassField = value;
                    this.RaisePropertyChanged("Pass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMyService")]
    public interface IMyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetAllUser", ReplyAction="http://tempuri.org/IMyService/GetAllUserResponse")]
        ConsoleApplication1.ServiceReference1.SinhVien[] GetAllUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetAllUser", ReplyAction="http://tempuri.org/IMyService/GetAllUserResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.SinhVien[]> GetAllUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetSvById", ReplyAction="http://tempuri.org/IMyService/GetSvByIdResponse")]
        ConsoleApplication1.ServiceReference1.SinhVien GetSvById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetSvById", ReplyAction="http://tempuri.org/IMyService/GetSvByIdResponse")]
        System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.SinhVien> GetSvByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/AddSv", ReplyAction="http://tempuri.org/IMyService/AddSvResponse")]
        int AddSv(string Name, string Email, string Phone, string Pass, int ClassID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/AddSv", ReplyAction="http://tempuri.org/IMyService/AddSvResponse")]
        System.Threading.Tasks.Task<int> AddSvAsync(string Name, string Email, string Phone, string Pass, int ClassID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/UpdateSv", ReplyAction="http://tempuri.org/IMyService/UpdateSvResponse")]
        int UpdateSv(int Id, string Name, string Email, string Phone, string Pass, int ClassID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/UpdateSv", ReplyAction="http://tempuri.org/IMyService/UpdateSvResponse")]
        System.Threading.Tasks.Task<int> UpdateSvAsync(int Id, string Name, string Email, string Phone, string Pass, int ClassID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/DeleteSvById", ReplyAction="http://tempuri.org/IMyService/DeleteSvByIdResponse")]
        int DeleteSvById(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/DeleteSvById", ReplyAction="http://tempuri.org/IMyService/DeleteSvByIdResponse")]
        System.Threading.Tasks.Task<int> DeleteSvByIdAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyServiceChannel : ConsoleApplication1.ServiceReference1.IMyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServiceClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.IMyService>, ConsoleApplication1.ServiceReference1.IMyService {
        
        public MyServiceClient() {
        }
        
        public MyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleApplication1.ServiceReference1.SinhVien[] GetAllUser() {
            return base.Channel.GetAllUser();
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.SinhVien[]> GetAllUserAsync() {
            return base.Channel.GetAllUserAsync();
        }
        
        public ConsoleApplication1.ServiceReference1.SinhVien GetSvById(int id) {
            return base.Channel.GetSvById(id);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication1.ServiceReference1.SinhVien> GetSvByIdAsync(int id) {
            return base.Channel.GetSvByIdAsync(id);
        }
        
        public int AddSv(string Name, string Email, string Phone, string Pass, int ClassID) {
            return base.Channel.AddSv(Name, Email, Phone, Pass, ClassID);
        }
        
        public System.Threading.Tasks.Task<int> AddSvAsync(string Name, string Email, string Phone, string Pass, int ClassID) {
            return base.Channel.AddSvAsync(Name, Email, Phone, Pass, ClassID);
        }
        
        public int UpdateSv(int Id, string Name, string Email, string Phone, string Pass, int ClassID) {
            return base.Channel.UpdateSv(Id, Name, Email, Phone, Pass, ClassID);
        }
        
        public System.Threading.Tasks.Task<int> UpdateSvAsync(int Id, string Name, string Email, string Phone, string Pass, int ClassID) {
            return base.Channel.UpdateSvAsync(Id, Name, Email, Phone, Pass, ClassID);
        }
        
        public int DeleteSvById(int Id) {
            return base.Channel.DeleteSvById(Id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteSvByIdAsync(int Id) {
            return base.Channel.DeleteSvByIdAsync(Id);
        }
    }
}
